language: ruby
before_install:
  - gem install bundler
rvm:
  - 2.1
  - 2.0
  - 1.9.3
script: bundle exec rake
notifications:
  irc: "irc.freenode.org#jekyll"
  email:
    on_success: never
    on_failure: never
