language: ruby
install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - travis_retry ./script/bootstrap
rvm:
  - 2.1
  - 2.0
  - 1.9.3
script: ./script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - irc.freenode.org#jekyll
    template:
      - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: never
