language: ruby
rvm:
  - 2.1
  - 2.0
  - 1.9.3
env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
sudo: false
before_script: bundle update
script: ./script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - irc.freenode.org#jekyll
    template:
      - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: never
