language: ruby
before_install:
  - gem install bundler
install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - travis_retry ./script/bootstrap
rvm:
  - 2.1
  - 2.0
  - 1.9.3
script: ./script/cibuild
notifications:
  irc: "irc.freenode.org#jekyll"
  email:
    on_success: never
    on_failure: never
